~Version Information
VERS.                      2.0: CWLS Log ASCII Standard - VERSION 2.0
WRAP.                       NO: One line per depth step
~Well Information Block
STRT.FT               -25.0000: START DEPTH
STOP.FT              2361.5000: STOP DEPTH
STEP.FT                 0.5000: STEP
NULL.                -999.2500: NULL VALUE
COMP.                      AEP: COMPANY
WELL.                   Pol 5H: WELL
FLD.                     Utica: FIELD
LOC.                          : LOCATION
CNTY.                  Belmont: COUNTY
SRVC.                         : SERVICE COMPANY
DATE.          Mon Jul 20 15-46-36 2015: LOG DATE
UWI.             34-013-2-0895: UNIQUE WELL ID
STAT.                       OH: STATE
~Curve Information Block
DEPT.FT            0 000 00 00: Depth
GR.                           : Gamma Ray
AMP3FT.MV                     : AMP3FT Amplitude
TT3FT.USEC                    : 3FT Travel Time
AMPS1.                        : AMPS1 Amplitude
AMPS2.                        : AMPS2 Amplitude
AMPS3.                        : AMPS3 Amplitude
AMPS4.                        : AMPS4 Amplitude
AMPS5.                        : AMPS5 Amplitude
AMPS6.                        : AMPS6 Amplitude
AMPS7.                        : AMPS7 Amplitude
AMPS8.                        : AMPS8 Amplitude
AMPS9.                        : AMPS9 Amplitude
AMPS10.                       : AMPS10 Amplitude
AMPS11.                       : AMPS11 Amplitude
AMPS12.                       : AMPS12 Amplitude
AMPS13.                       : AMPS13 Amplitude
AMPS14.                       : AMPS14 Amplitude
AMPS15.                       : AMPS15 Amplitude
AMPS16.                       : AMPS16 Amplitude
~Parameter Information Block
~A  Depth        GR        AMP3FT      TT3FT       AMPS1       AMPS2       AMPS3       AMPS4       AMPS5       AMPS6       AMPS7       AMPS8       AMPS9       AMPS10      AMPS11      AMPS12      AMPS13      AMPS14      AMPS15      AMPS16   
   -25.0000   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500   -999.2500